name: 'Build'
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  artifacts:
    name : 'Create release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

      # Create a zip from what's in this repo
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: 'dist/'
        path: '../'
        filename: 'stable.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig dist'
        command: "mkdir -p dist"

    # List all the files that have been created
    - name: 'List files'
      run: |
        find dist/ -maxdepth 2  -type f

    - uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.SPACE_ACCESS_KEY}}
        secret_key: ${{ secrets.SPACE_SECRET_KEY }}
        space_name: ${{ secrets.SPACE_NAME }}
        space_region: ${{ secrets.SPACE_REGION }}
        cdn_domain: ${{ secrets.SPACE_CDN_DOMAIN }}
        source: dist
        out_dir: configs
